import { RepositoryItem, PaperReview, CommunityChannel } from './types';

export const INITIAL_REPOSITORIES: RepositoryItem[] = [
  {
    id: 'res-1',
    courseCode: 'CS504',
    title: 'CS504 Software Engineering 1',
    description: 'Midterm Solved Past Papers 2024-25 by Abdul Majid',
    section: 'pastpapers',
    fileType: 'PDF',
    downloads: 14280,
    status: 'live',
    highlighted: true,
    uploadedAt: 'Yesterday',
    size: '18.4 MB',
  },
  {
    id: 'res-2',
    courseCode: 'CS601',
    title: 'CS601 Data Communications',
    description: 'Assignment #1 100% Correct Verified Solution',
    section: 'assignments',
    fileType: 'DOC',
    downloads: 8410,
    status: 'live',
    highlighted: true,
    uploadedAt: '2 days ago',
    size: '2.1 MB',
  },
  {
    id: 'res-3',
    courseCode: 'MTH101',
    title: 'MTH101 Calculus and Analytical Geometry',
    description: 'Short Handouts Highlighted Key Points (Lessons 1-22)',
    section: 'handouts',
    fileType: 'ZIP',
    downloads: 31590,
    status: 'live',
    highlighted: true,
    uploadedAt: '3 days ago',
    size: '45.2 MB',
  },
  {
    id: 'res-4',
    courseCode: 'CS201',
    title: 'CS201 Introduction to Programming',
    description: 'Spring 2025 Midterm GDB Solution (Draft Mode)',
    section: 'gdbs',
    fileType: 'PDF',
    downloads: 0,
    status: 'hidden',
    highlighted: false,
    uploadedAt: '4 hours ago',
    size: '1.4 MB',
  },
  {
    id: 'res-5',
    courseCode: 'CS304',
    title: 'CS304 Object Oriented Programming',
    description: 'Grand Quiz Mega File: 1,200 Solved MCQs with Code Snippets',
    section: 'quizzes',
    fileType: 'PDF',
    downloads: 22450,
    status: 'live',
    highlighted: true,
    uploadedAt: '5 days ago',
    size: '12.8 MB',
  },
  {
    id: 'res-6',
    courseCode: 'ENG101',
    title: 'ENG101 English Comprehension',
    description: 'Highlighted Vocabulary, Idioms & Solved Midterm Papers',
    section: 'handouts',
    fileType: 'PDF',
    downloads: 19820,
    status: 'live',
    highlighted: false,
    uploadedAt: '1 week ago',
    size: '8.6 MB',
  },
  {
    id: 'res-7',
    courseCode: 'ECO401',
    title: 'ECO401 Economics & Microeconomics',
    description: 'Waqar Sidhu & Moaaz Combined Finalterm Super Archive',
    section: 'pastpapers',
    fileType: 'PDF',
    downloads: 16730,
    status: 'live',
    highlighted: true,
    uploadedAt: '1 week ago',
    size: '24.1 MB',
  },
  {
    id: 'res-8',
    courseCode: 'MGT211',
    title: 'MGT211 Introduction to Business',
    description: 'Solved GDB & Case Analysis with Reference Answers',
    section: 'gdbs',
    fileType: 'DOC',
    downloads: 9140,
    status: 'live',
    highlighted: false,
    uploadedAt: '2 weeks ago',
    size: '1.9 MB',
  },
];

export const INITIAL_REVIEWS: PaperReview[] = [
  {
    id: 'rev-1',
    courseCode: 'CS304',
    examType: 'Midterm Paper',
    campus: 'Lahore Campus',
    difficulty: 'Moderate',
    rating: 4.5,
    content: 'Almost 80% MCQs repeated from Waqar Sidhu Midterm mega files! 3-mark question asked differences between Pure Virtual Function vs Virtual Function. 5-mark question required writing Operator Overloading syntax for "+" operator.',
    author: 'ScholarHamza_VU',
    timeAgo: '12m ago',
    timestamp: Date.now() - 12 * 60 * 1000,
    helpfulCount: 84,
    verified: true,
    featured: true,
    status: 'published',
  },
  {
    id: 'rev-2',
    courseCode: 'MTH101',
    examType: 'Midterm Exam',
    campus: 'Rawalpindi Hub',
    difficulty: 'Hard',
    rating: 4.8,
    content: 'Calculus derivatives & limits dominated. Make sure to prepare Sandwich Theorem proof and L\'Hopital rule questions. MCQs had trigonometric inverse identities straight out of highlighted Handout chapter 12.',
    author: 'Anonymous Scholar',
    timeAgo: '34m ago',
    timestamp: Date.now() - 34 * 60 * 1000,
    helpfulCount: 52,
    verified: true,
    featured: false,
    status: 'published',
  },
  {
    id: 'rev-3',
    courseCode: 'ENG101',
    examType: 'Midterm Paper',
    campus: 'Karachi Center',
    difficulty: 'Easy',
    rating: 4.0,
    content: 'Reading comprehension passage was easy. Synonym and antonym questions directly from lesson 1 to 14. 5-mark subjective was writing a formal memo to department head.',
    author: 'Ayesha_VU_VIP',
    timeAgo: '1h ago',
    timestamp: Date.now() - 60 * 60 * 1000,
    helpfulCount: 96,
    verified: true,
    featured: false,
    status: 'published',
  },
  {
    id: 'rev-4',
    courseCode: 'CS504',
    examType: 'Midterm Today at 09:30 AM',
    campus: 'Lahore Campus',
    difficulty: 'Moderate',
    rating: 5.0,
    content: 'Almost 85% of MCQs were straight from Abdul Majid Sir\'s mega files! Subjective part had 2 questions on SRS requirements and 1 on Architecture diagrams. Highly recommend everyone to download the handout notes.',
    author: 'Zainab S. (BC210408892)',
    timeAgo: '18m ago',
    timestamp: Date.now() - 18 * 60 * 1000,
    helpfulCount: 42,
    verified: false,
    featured: false,
    status: 'pending',
  },
  {
    id: 'rev-5',
    courseCode: 'CS601',
    examType: 'Midterm Today at 12:00 PM',
    campus: 'Rawalpindi Campus',
    difficulty: 'Hard',
    rating: 4.5,
    content: 'Transmission media and OSI 7 Layer models were heavily asked in 5-mark subjective questions. Uploading my scanned rough question paper sheet for fellow batchmates.',
    author: 'Hamza R. (MC220201455)',
    timeAgo: '42m ago',
    timestamp: Date.now() - 42 * 60 * 1000,
    helpfulCount: 29,
    verified: false,
    featured: false,
    status: 'pending',
    hasAttachment: true,
  },
];

export const COMMUNITY_CHANNELS: CommunityChannel[] = [
  {
    id: 'chan-1',
    title: 'VU INSIGHT Elite Broadcast',
    category: 'OFFICIAL CHANNEL',
    description: 'Central feed curated personally by Abdul Majid. Handout revisions, date-sheet schedules, and breaking LMS alerts.',
    icon: 'podcasts',
    url: 'https://whatsapp.com/channel/0029VaAbdulMajidVUCrew',
    members: '18.4K Members',
    accent: 'cyan',
  },
  {
    id: 'chan-2',
    title: 'CS Scholars Wing',
    category: 'COMPUTER SCIENCE',
    description: 'Dedicated coders syndicate for CS101, CS201, CS304, CS504, CS601. Code sharing and compiler troubleshooting.',
    icon: 'terminal',
    url: 'https://chat.whatsapp.com/invite/VUCrewCSCodersWing',
    members: '1,024 / 1,024 Active',
    accent: 'violet',
  },
  {
    id: 'chan-3',
    title: 'Management Wing',
    category: 'BUSINESS & MGT',
    description: 'Specialist matrix for MGT101, MGT211, ECO401, FIN622, and MKT501. Case study analysis and GDB discussion.',
    icon: 'insights',
    url: 'https://chat.whatsapp.com/invite/VUCrewManagementScholars',
    members: '980 Active',
    accent: 'gold',
  },
  {
    id: 'chan-4',
    title: 'Live Paper Alert VIP',
    category: 'EXAM ALERTS',
    description: 'Active only during examination weeks. Instant notification as soon as students step out of VU exam halls.',
    icon: 'notifications_active',
    url: 'https://chat.whatsapp.com/invite/VUCrewLiveExamAlerts',
    members: '2,400+ Watchers',
    accent: 'cyan',
  },
];

export const ASSETS = {
  emblem: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAoBIYf1v-EngQMdd6rMd7LBJlYOuGjUOUmVjbfd0LoBvXFijPQT6mlBVd8RLwKjUc5zxLsAfKE1goZJg0MCnVn8NmQ0MvugmEr_x7XFHZurYssnlfi6HM8xsEc62ZMTPBZ_nmsN14DmCwTFKZGoTIB3XI9NvECWgmDGnQ8AJBBiQQy8D74mXdck5Gxi2-i3fLZtxtA9wCOf-KRjFlSGzmyfl5nkoMFzeizYv-qbZBSGBiarhRLfiUAKg',
  profileUser: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDRtTh8QqCq60DNGy83tqvPg1ByG1LxE74ASkGmMH54yLOFUpsCGRiNcoGfHeB36-GcAFC5yzx7X4tba1Pt134NUP-SWgYx8m-c2lTD4GSK_Q0Xcs05Uv0SqSq4gzzZUdFQMhInfMe-il5cQCIf7FQftQb71nPWXmTHdEHrxth8VyIF0_cr-l6Rzu2N2XW1Qv6V95pXvCIrSs4LTyHvlD-Ci1lIr9PXfgfYJpDqbi9dC6Nsold0z66GUA',
  profileScholar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBKMsSb-aGx98GURcVWwH1pVMmNkATkLxMayEhN-ZG7dpL3ZYQROOHPZmAWCqBOKjEPX-03o0PsXV_8x697oBldiJveA2n8eCz8HVapeD19slpMy8u9XoCEdjeR617weFHDM3p-h48SiPpCRAVsnoj28MGFpE1-dPE8S2KkGBYJqFjxAsE8jq_ftom8U1CnlQqBRlBG10seEQEp4SyMzC4SpJrhC2l-HA1uNirk5Q2X4qZ4Lw9xhIH-3Q',
  adminEmblem: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA28pIIZY94uDis5h1EQPRQWGlHBu408EG930QRu-2eHdqh17VkeTlxW3HPjBc91e6AWPed9fp2YOClqcW_X56wrvHyCn3MVK7DoO_uuV2UNj1SON5NWcTl0EEdbaXf6Lj3ev4ExHud4fbLRCOHts4h30Byx84wiUepSKXd4LV_oF2aKvblU4uJVhzkyjV-D3d7q0xZEIFyjum8JqGkIUHJ-K6Orlc2RtGV7SfBqkZXAyC9ECpHiEs9rA',
};
